#
# Triangular, pentagonal, and hexagonal, v1
# https://projecteuler.net/problem=45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle    T_n=n(n+1)/2    1, 3, 6, 10, 15, ...
# Pentagonal    P_n=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal    H_n=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T_285 = P_165 = H_143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
#


def run():
    # Why 100000? No idea, just put something there, and it gives the correct answer...
    # That is soooo cheating :D
    triangle_penta_hexa = (
        set(n * (n + 1) // 2 for n in range(286, 100000))
        & set(n * (3 * n - 1) // 2 for n in range(165, 100000))
        & set(n * (2 * n - 1) for n in range(143, 100000))
    )
    print('Result:', triangle_penta_hexa.pop())
